server:
  port: 8890
spring:
  application:
    name: config-server
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/smartdt/springcloudconfig.git #配置Git仓库位置。
          searchPaths: config-repo #配置仓库路径下的相对搜索位置，可以配置多个。
          username: xxx
          password: xxx
          default-label: master #配置仓库的分支
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:5555/eureka/
  instance:
      prefer-ip-address: true
      lease-expiration-duration-in-seconds: 30
      lease-renewal-interval-in-seconds: 10

