server:
  port: 1000

spring:
  application:
    name: microserver-1000-client
  #rabbitmq
  rabbitmq:
    host: 118.89.237.88
    port: 5672
    username: root
    password: root123

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:5555/eureka/
  instance:
      prefer-ip-address: true
      lease-expiration-duration-in-seconds: 30
      lease-renewal-interval-in-seconds: 10




