server:
  port: 2000

spring:
  application:
    name: microserver-2000-client
  #rabbitmq
  rabbitmq:
    host: 118.89.237.88
    port: 5672
    username: root
    password: root123

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:5555/eureka/
  instance:
      prefer-ip-address: true
      lease-expiration-duration-in-seconds: 30
      lease-renewal-interval-in-seconds: 10
management:
  endpoint:
    health:
      show-details: always #健康情况-展示全部详情，否则只展示status信息
fegin:
  hystrix:
    enabled: true  #打开 feign与hystrix开关

zuul:
  routes:
    api-a:
      path: /ribbon/**
      serviceId: service-ribbon  #如果是/ribbon/**路径下的请求，则跳转到service-ribbon
    api-b:
      path: /feign/**
      serviceId: service-feign  #如果是/feign/**路径下的请求，则跳转到service-feign

